/*
===============================================================================
Magnitude Analysis: Quantitative Insights
===============================================================================
*/

-------------------------------------------------------------------------------
--Magnitude Analysis (Quantitative Insights)
-------------------------------------------------------------------------------

--Find total customers by countries
SELECT
country,
COUNT(customer_key) AS Total_Customer
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_Customer DESC

--Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS Total_Customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_Customer DESC

--Find total products by category
SELECT
category,
COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the average cost in each category?
SELECT
category,
AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--What is the total revenue generated for each category?
SELECT
p.category,
SUM(f.sales_amount) Total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY Total_revenue DESC

--Find total revenue generated by each customer
SELECT
c.customer_key,
c.First_name,
c.Last_name,
SUM(f.sales_amount) Total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON  f.customer_key = c.customer_key
GROUP BY 
c.customer_key, 
c.First_name,
c.Last_name
ORDER BY Total_revenue DESC

--What is the distribution of sold items across countries?

SELECT
c.country,
SUM(f.sales_amount) Total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON  f.customer_key = c.customer_key
GROUP BY 
c.country
ORDER BY Total_revenue DESC

/*
===============================================================================
Ranking
===============================================================================
*/

--Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) Total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY Total_revenue DESC

SELECT
*
FROM(
	SELECT 
	p.product_name,
	SUM(f.sales_amount) Total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales AS f
	LEFT JOIN gold.dim_products AS p
	ON f.product_key = p.product_key
	GROUP BY p.product_name
)t WHERE rank_products <= 5

--Which 5 subcategory generate the highest revenue?
SELECT TOP 5
p.subcategory,
SUM(f.sales_amount) Total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.subcategory
ORDER BY Total_revenue DESC

--What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) Total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY Total_revenue ASC

--3 customers with the fewest orders placed 

SELECT TOP 3
c.customer_key,
c.First_name,
c.Last_name,
COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON  f.customer_key = c.customer_key
GROUP BY 
c.customer_key, 
c.First_name,
c.Last_name
ORDER BY total_orders 